INSERT INTO SKIPASS(ID, ID_SKI_PASS, OWNER_LAST_NAME, OWNER_FIRST_NAME) VALUES(RANDOM_UUID(), 200, 'Doe', 'John');
INSERT INTO RESORT(ID, ID_RESORT, RESORT_NAME, HOURLY_GROSS_PRICE) VALUES(RANDOM_UUID(), 1, 'Les Karellis', '2.50');
INSERT INTO RESORT(ID, ID_RESORT, RESORT_NAME, HOURLY_GROSS_PRICE) VALUES(RANDOM_UUID(), 2, 'Aillons-Margériaz', '3.50');
INSERT INTO RESORT(ID, ID_RESORT, RESORT_NAME, HOURLY_GROSS_PRICE) VALUES(RANDOM_UUID(), 3, 'Le Collet D''Allevard', '4.50');
INSERT INTO RESORT(ID, ID_RESORT, RESORT_NAME, HOURLY_GROSS_PRICE) VALUES(RANDOM_UUID(), 4, 'Les 7 Laux', '5.50');